#pragma once
#include <iostream>
#include <fstream>
#include <algorithm>
#include <windows.h>
#include <iomanip>
#include <string>
#include <vector>
#include <set>
#include <map>

#include "User.hpp"
#include "Card.hpp"
#include "Category.hpp"
#include "Date.hpp"
#include "Expense.hpp"
#include "functions.hpp"
#include "Report.hpp"
#include "ReportGenerator.hpp"
#include "Time.hpp"
#include "Wallet.hpp"